- readme.md
/cc @xtreamwayz @weierophinney
> update readme: title, badge, composer command, screenshot

- src/Composer/config.php
in case https://github.com/zendframework/zend-expressive-zendviewrenderer/pull/1 accepted ;)
> alternative fixes for zend-expressive-skeleton/#4

- config/autoload/dependencies.global.php
- src/Composer/Resources/config/routes-aura-router.php
- src/Composer/Resources/config/routes-fast-route.php
- src/Composer/Resources/config/routes-zf2-router.php
> Actions dependencies in the right place

- public/.htaccess
APP_ENV behavior was removed on https://github.com/xtreamwayz/expressive-composer-installer/pull/13
> Remove obsolete APP_ENV

- src/ExpressiveInstaller/config.php
> Update grammar for installer prompts

- README.md
- composer.json
24 hrs seems enough of a working day
> don't let composer timeout after 300 seconds

- config/autoload/middleware-pipeline.global.php
> Add error config for error middleware pipeline, fixes #65

- src/ExpressiveInstaller/Resources/templates/plates-home-page.phtml
- src/ExpressiveInstaller/Resources/templates/plates-layout.phtml
- src/ExpressiveInstaller/Resources/templates/twig-home-page.html.twig
- src/ExpressiveInstaller/Resources/templates/twig-layout.html.twig
- src/ExpressiveInstaller/Resources/templates/zend-view-home-page.phtml
- src/ExpressiveInstaller/Resources/templates/zend-view-layout.phtml
if https://github.com/zendframework/zend-expressive/pull/279 will be merged /cc @xtreamwayz @weierophinney
> update link resources to uses gh-pages url

- README.md
It really helps if I create a pull request on the zendframework namespace instead of my own :)
> Add troubleshooting documentation

- public/index.php
Because using strings is so 2012.
> Changes using a string to using class constant

- src/App/src/Action/HomePageAction.php
Any reason to check for template after `if ($this->template instanceof PlatesRenderer)`? For me looks like if template not added we can return JsonResponse with welcome message immediately.
> Move template check in HomePageAction

- config/autoload/dependencies.global.php
zendframework/zend-expressive#465
> Convert DefaultDelegate::class to string

- CHANGELOG.md
@weierophinney I guess you use some kind of script to update this file and forgot to configure this no? If so it's time to fix this :D
> fixed broken links in CHANGELOG.md

- composer.json
- Always use `0.0.0.0` for IP address, to allow it to listen on any adapter.
- Always use a trailing `/` with the `-t` argument, to ensure assets and script resolve correctly (otherwise they are appended with no directory separator).
- Pass script to run _relative to_ target path (`-t` argument).
> Update `composer serve` to work cross-platform

- src/ExpressiveInstaller/OptionalPackages.php
It could be alias root package or real root package.
It resolves issue with creating project from dev version.
Resolves #193
> Modify dependencies on original package from event

- public/index.php
> change call_user_func usage to invoked function  at index.php for expressive 3

- src/ExpressiveInstaller/Resources/templates/plates-home-page.phtml
- src/ExpressiveInstaller/Resources/templates/plates-layout.phtml
- src/ExpressiveInstaller/Resources/templates/twig-home-page.html.twig
- src/ExpressiveInstaller/Resources/templates/twig-layout.html.twig
- src/ExpressiveInstaller/Resources/templates/zend-view-404.phtml
- src/ExpressiveInstaller/Resources/templates/zend-view-error.phtml
- src/ExpressiveInstaller/Resources/templates/zend-view-home-page.phtml
- src/ExpressiveInstaller/Resources/templates/zend-view-layout.phtml
This PR updates:
- Bootstrap to [version 4.0](https://getbootstrap.com)
- Font-Awesome to [version 4.7](http://fontawesome.io) (version 5 is already finalized, but not included in this PR)
- jQuery to [version 3.3.1](https://jquery.com)
The layout has been kept as much as possible!
Cheers,
LT.
> Update to Bootstrap 4

- config/pipeline.php
Use the DispatchMiddleware and PathBasedRoutingMiddleware in the pipeline.
> Fix the pipeline for the zend-expressive 3.0.x release

- composer.json
- src/ExpressiveInstaller/config.php
- test/AppTest/Action/HomePageActionTest.php
- test/AppTest/Action/PingActionTest.php
- test/ExpressiveInstallerTest/ContainersTest.php
- test/ExpressiveInstallerTest/ProjectSandboxTrait.php
- test/ExpressiveInstallerTest/RoutersTest.php
- test/ExpressiveInstallerTest/TemplateRenderersTest.php
Updates the installer optional dependency constraints to use alpha or greater stability wherever possible.
Fixes imports in the `App` module test suite to ensure they pass.
> Dependecy and test fixes

- CHANGELOG.md
- LICENSE.md
- composer.json
- config/config.php
- config/pipeline.php
- test/ExpressiveInstallerTest/ProjectSandboxTrait.php
with also update the `Zend\Expressive\Handler\NotFoundHandler` usage in favor of removed `Zend\Expressive\Middleware\NotFoundMiddleware`
> update to use expressive alpha6

- CHANGELOG.md
- src/ExpressiveInstaller/OptionalPackages.php
- test/ExpressiveInstallerTest/ProcessAnswersTest.php
> Fix conditions where whitelisted packages are removed

- composer.json
- src/ExpressiveInstaller/config.php
This version is compatible with zend-container-config-test ^0.2:
http://github.com/zendframework/zend-container-config-test/releases/tag/0.2.0
> Updated to zend-sf-di-config 0.3

- .gitignore
> remove empty line in the middle of .gitignore lines
