zendframework/zend-expressive-skeleton

composer.json, src/Action/HomePageAction.php, src/Action/HomePageFactory.php, src/Composer/Resources/config/templates-plates.php, src/Composer/Resources/config/templates-twig.php, src/Composer/Resources/config/templates-zend-view.php, src/Composer/config.php, test/Action/HomePageFactoryTest.php
- Sets the default router to FastRoute.
- Updates the templates to refer to `TemplateRendererInterface`, and to use the `Renderer` suffix for concrete implementations.
- Updates the routers to refer to routers using the `Router` suffix.
=> Updates to Expressive 0.4.0

composer.json, config/config.php
As discussed here: zendframework/zend-expressive#150
It fixes auto loading configuration files. This happens when routes are split in different files.
I'm not sure if zend-stdlib should be made a dependency since it is already included in zend-expressive.
=> Use zend-stdlib for autoload config

src/Composer/OptionalPackages.php
The composer source is only needed for developing the installer so it can be removed.
=> Remove composer source dev dependency

src/Composer/OptionalPackages.php, src/Composer/Resources/config/routes-minimal-aura-router.php, src/Composer/Resources/config/routes-minimal-fast-route.php, src/Composer/Resources/config/routes-minimal-zf2-router.php, src/Composer/config.php
Asks before any questions whether or not to do a minimal installation.  If so, it uses a different set of files to copy ("minimal-files" in the configuration), and, when all questions have been answered and changes completed, removes the middleware files and public assets.
Provides a solution for #17.
=> Added ability to specify minimal install

composer.json, config/autoload/dependencies.global.php, config/autoload/middleware-pipeline.global.php, src/Composer/Resources/config/templates-zend-view.php, src/Composer/config.php
This patch adds zend-expressive-helpers to the skeleton, which allows us to ship the `UrlHelper` and `ServerUrlHelper` by default.
It also means that the customizations for adding URL helper awareness to the zendviewrenderer configuration becomes obsolete, so this functionality was removed; as that functionality has not been in a release, the change is backwards compatible.
=> Add zend-expressive-helpers

CHANGELOG.md, composer.json, config/autoload/middleware-pipeline.global.php
- Updated version constraint in `composer.json`
- Added dependencies and pre_routing middleware-pipeline entries for `Zend\Expressive\Helper\UrlHelperMiddleware` to ensure the middleware is registered by default, ensuring the `UrlHelper` will be updated with the `RouteResult`.
This fixes issues reported and commented on in an [issue on Expressive](https://github.com/zendframework/zend-expressive/issues/186#issuecomment-162941737), ensuring the `UrlHelper` is properly seeded.
=> Updated to zend-expressive-helpers 1.2.0

src/Composer/Resources/config/templates-zend-view.php
- Adds a factory entry for the `HelperPluginManager`.
- Adds a configuration section for defining view helper services.
Starts addressing zendframework/zend-expressive#217
=> Add configuration for view helpers

config/config.php
With the current glob, there are four type of config file loaded, so the comment in `config.php` needs to show the order that they are all loaded.
=> Be more explicit about order of loading config files

config/config.php
Use var_export to write the merged config array to disk. This means that we can load the config back using a simple include and avoid a `json_decode()` call.
=> Cache config to a PHP array

src/Composer/Resources/config/templates-twig.php
According to the changelog for [Expressive Twig Renderer 0.3.0](https://github.com/zendframework/zend-expressive-twigrenderer/releases/tag/0.3.0) it changed its config to:
```php
'templates' => [
'extension' => 'file extension used by templates; defaults to html.twig',
'paths' => [
// namespace / path pairs
//
// Numeric namespaces imply the default/main namespace. Paths may be
// strings or arrays of string paths to associate with the namespace.
],
],
'twig' => [
'cache_dir' => 'path to cached templates',
'assets_url' => 'base URL for assets',
'assets_version' => 'base version for assets',
'extensions' => [
// extension service names or instances
],
],
```
=> Use new twig config key

README.md
While this project sits at RC stage, you need to be more specific about which version to use. The .5 version (stable) is broken now due to changes in the other zend-expressive projects.
=> Update docs to pull @rc

config/autoload/middleware-pipeline.global.php
The expressive [cookbook](https://github.com/zendframework/zend-expressive/blob/master/doc/book/cookbook.md) indicates that we can use arrays of middleware here.
=> Update to new middleware array syntax

README.md, composer.json
Executes `php -S 0.0.0.0:8080 -t public/`, starting up the built-in webserver from PHP:
```bash
$ composer serve
```
=> Added composer "serve" command

src/ExpressiveInstaller/Resources/templates/zend-view-layout.phtml
Fixed the wrong usage of the `headScript()` view helper for the external js files to use the `inlineScript()` view helper. Also moved the addition of the external css and js files to the top for an better overview. Now you have the definition of all external files in one place while they are echoed where needed.
=> Fixed wrong view helper usage for external js files #44

composer.json, src/ExpressiveInstaller/Resources/config/container-pimple.php, src/ExpressiveInstaller/config.php, test/ExpressiveInstallerTest/ContainersTest.php
As discussed on IRC last night.
@weierophinney **NOTE**: Because of the new tests you have to make a choice if you want pimple 1 or 3 support. You can't have both since all dependencies are loaded once. This pull request has to be rebased and updated once the new tests are merged from #48.
=> Add Pimple 3 support

composer.json
Without this routes with extensions (etc .html, .css) don't routing by expressive.
=> Set index.php as router in serve command

public/.htaccess
The change in this patch is introduced after testing several debug bars.
The Apache `.htaccess` rules were updated to remove a section that was specifically matching web assets by extension (including CSS, JS, fonts, and most image formats). This rule was removed for the following reasons:
- The preceding rule would prevent it from triggering in most cases already, as it checks to see if the request is for a file on the filesystem, and, if so, returns it immediately.
- If the preceding rules failed, we likely want to serve the request through the web application (e.g., via Assetic, vfs, etc.). The rules as written would prevent that from happening.
=> Updated Apache asset rules

src/App/Action/HomePageAction.php
At the moment the string `Get started with $templateName` is never shown because of a wrong namespace.
=> use correct namespaces in HomePageAction to show links to template engines

src/ExpressiveInstaller/Resources/config/container-zend-servicemanager.php
Hello,
I wanted to give this skeleton a try. So I just did ``composer create-project zendframework/zend-expressive-skeleton`` but directly ran into the following error after install :
``Fatal error: Uncaught TypeError: Argument 1 passed to Zend\ServiceManager\ServiceManager::__construct() must be of the type array, object given``
I had chosen : FastRoute, Zend\ServiceManager and Twig as dependencies.
It appears that the installer made me download Zend\ServiceManager v3 as dependency. This PR fixes the config file to be compliant with v3, whose constructor expects an array to be injected.
=> Add Zend\ServiceManager v3 compatibility

README.md, composer.json, config/autoload/middleware-pipeline.global.php, src/ExpressiveInstaller/config.php
This patch provides a few changes to prepare for RC6:
- It updates the zend-servicemanager version constraint to `^2.7.3 || ^3.0`, to allow users to select the version they want to use. Configuration already works with either.
- It updates the zend-expressive-helpers dependency to `^2.0`, as that's the version compatible with zend-expressive RC6.
- It updates the `middleware_pipeline` to follow the changes in zend-expressive RC6, providing a list of middleware specifications with priority values, and creating the following specific definitions:
- "always" is registered at priority 10000, and represents a pipeline of middleware that acts as either pre-conditions or post-routing handlers (e.g., CORS support, WWW-Authentication header injection, etc.).
- "routing" is registered at priority …
=> Prepare for RC6

README.md, src/ExpressiveInstaller/OptionalPackages.php
This fixes #62.
Only issue left is that during creating the project whoops 2.0 is installed. When running ``composer update`` it is changed to 1.x. A temporary work around is to update to whoops 2.x?
=> Remove dev dependencies properly from composer

composer.json
composer update after composer create project got filp/whoops == 2.0.0 not found, fill with ^2.0 should make it works.
=> use filp/whoops ^2.0

src/ExpressiveInstaller/Resources/config/container-pimple.php
just an idea based on zend-servicemanager v3:
- stores the factory in the container
- allows reuse of the same factory (and same instance) for more than one service
- pass an extra parameter to the factory in order to make it possible to identify the requested service
Naming:
should we change $object to $factoryClass and $invokableClass to make it more explicit?
=> factory sharing for pimple container

composer.json, src/ExpressiveInstaller/config.php
The filp/whoops version was updated in composer.json to ``^1.1 || ^2.0`` but not in the config. This might have been the cause for some issues during installation like #71.
Also expressive is stable now, so we might as well go for stable versions only.
=> Update package requirements

src/ExpressiveInstaller/config.php
This PR mitigates #79 (does not solve it - only mitigates the problem, for now), by allowing `ocramius/proxy-manager:^2.0` installation
zendframework/zend-servicemanager#103 is also related, although not strictly required (changes only in the test-suite)
=> Allowing ProxyManager v2 installation

src/ExpressiveInstaller/OptionalPackages.php
The version was not properly added to the package, which causes composer to install the latest package even if it was higher than the required version.
fixes #79
fixes #71
fixes Ocramius/PSR7Session#47
=> Use version constraint when adding a package

src/ExpressiveInstaller/Resources/templates/plates-error.phtml, src/ExpressiveInstaller/Resources/templates/twig-error.html.twig, src/ExpressiveInstaller/Resources/templates/zend-view-error.phtml
closes #77 
Dumping the exception was never meant to make it into a stable release. Exceptions including stack traces can get pretty big. If you need something to debug your app, use tools like [whoops](https://zendframework.github.io/zend-expressive/features/error-handling/#whoops).
=> Remove dumping the exceptions

src/ExpressiveInstaller/OptionalPackages.php, test/ExpressiveInstallerTest/RemoveComposerLockTest.php
=> Added installer option to remove composer.lock file from .gitignore file

composer.json
Updates the version constraints to allow either the 2.7 or 3.0 series of zend-stdlib.
=> Allow zend-stdlib 3.0

src/ExpressiveInstaller/Resources/config/container-pimple.php
storing object having a callable `__invoke()` method requires using Pimple::protect().... I (foolishly) forgot this in my previous commit.
=> pimple protect factory

src/ExpressiveInstaller/Resources/config/container-pimple.php
- supports factories with pimple extend style signature using a new key "extensions" under "dependencies"
- supports zend-servicemanager3 delegator style signature re-using the "delegators" key. This could help if switching from/to zend-servicemanager3/pimple
=> add support for pimple-extend in config

src/ExpressiveInstaller/OptionalPackages.php
Allow full install for `n || N || 2`, anything else triggers a minimal install
It turns out mistakes can be made here (capslock, thinking the second answer can be chosen with `2`). Those answers are now valid as well.
closes #94
=> Allow full install for `n || N || 2`

composer.json, src/ExpressiveInstaller/OptionalPackages.php, src/ExpressiveInstaller/config.php
It is only suggested by zend-servicemanager and not a required dependency. Therefor there is no need to add it.
Fixes #99
=> Remove the proxy-manager as a dev dependency

src/ExpressiveInstaller/OptionalPackages.php
Whoops should be removed from require-dev as well during the cleanup phase. If not the package will always be installed by composer even if an user answered with "none of the above".
Thanx to @Koopzington for reporting this in #99
=> Force removal of whoops during the cleanup phase

.coveralls.yml, .gitignore, .travis.yml, README.md, composer.json, phpunit.xml.dist, src/ExpressiveInstaller/OptionalPackages.php, test/ExpressiveInstallerTest/AddPackageTest.php, test/ExpressiveInstallerTest/ContainersTest.php, test/ExpressiveInstallerTest/ErrorHandlerTest.php, test/ExpressiveInstallerTest/InstallerTestCase.php, test/ExpressiveInstallerTest/ProcessAnswersTest.php, test/ExpressiveInstallerTest/RemoveDevDependenciesTest.php, test/ExpressiveInstallerTest/RemoveInstallerTest.php, test/ExpressiveInstallerTest/RequestMinimalTest.php, test/ExpressiveInstallerTest/RoutersTest.php, test/ExpressiveInstallerTest/TemplateRenderersTest.php
=> Refactor and improve tests

composer.json
In commit ea36f0aa27e2e74f0a0a93ede4aff5f692250796 the script was renamed to cs-check for consistency. However the reference in the check script was left untouched.
=> Fix composer check script

src/ExpressiveInstaller/OptionalPackages.php
As discussed in #98, this PR removes some zendframework related docs after setup.
Closes #98.
=> Remove CHANGELOG.md, CONDUCT.md and CONTRIBUTING.md after setup

composer.json
Document root path with '/' in the end of document root seems not to work on Windows (while works on Ubuntu). Removing it works on both (Windows & Ubuntu).
fixes #103
=> Do not suffix document root with '/'

.travis.yml, composer.json, src/ExpressiveInstaller/Resources/config/templates-twig.php
Register the new TwigEnvironmentFactory which was introduced with zendframework/zend-expressive-twigrenderer#15 in version 1.2.0.
This is a hotfix for #126. It's already included in the develop branch.
=> Register the new TwigEnvironment

.travis.yml, composer.json, src/ExpressiveInstaller/OptionalPackages.php, src/ExpressiveInstaller/Resources/config/container-aura-di.php, src/ExpressiveInstaller/Resources/config/templates-plates.php, src/ExpressiveInstaller/Resources/src/ExpressiveAuraDelegatorFactory.php, src/ExpressiveInstaller/config.php, test/ExpressiveInstallerTest/AddPackageTest.php, test/ExpressiveInstallerTest/ContainersTest.php, test/ExpressiveInstallerTest/CopyResourceTest.php, test/ExpressiveInstallerTest/ErrorHandlerTest.php, test/ExpressiveInstallerTest/OptionalPackagesTestCase.php, test/ExpressiveInstallerTest/ProcessAnswersTest.php, test/ExpressiveInstallerTest/PromptForOptionalPackagesTest.php, test/ExpressiveInstallerTest/RemoveDevDependenciesTest.php, test/ExpressiveInstallerTest/RemoveInstallerTest.php, test/ExpressiveInstallerTest/RemoveLineFromStringTest.php, test/ExpressiveInstallerTest/RequestInstallTypeTest.php, test/ExpressiveInstallerTest/RoutersTest.php, test/ExpressiveInstallerTest/SetupDataAndCacheDirTest.php, test/ExpressiveInstallerTest/TemplateRenderersTest.php, test/ExpressiveInstallerTest/UpdateRootPackageTest.php
Please see commits descriptions for more details
=> General fixes for 2.0 release

config/autoload/development.local.php.dist, src/ExpressiveInstaller/OptionalPackages.php, src/ExpressiveInstaller/Resources/config/error-handler-whoops.php, src/ExpressiveInstaller/config.php, test/ExpressiveInstallerTest/ErrorHandlerTest.php, test/ExpressiveInstallerTest/ProjectSandboxTrait.php
It makes most sense to put the Whoops configuration in development mode; this patch accomplishes that.
Additionally, it updates the `config/autoload/development.local.php.dist` file to remove the import statement on the `ConfigAggregator`, as it was unnecessary.
=> Write whoops configuration to development.local.php.dist

public/index.php
The skeleton actually requires files through its index file:
- config/config.php
- config/container.php (dynamically created)
Those files expose few variables ($container, $cachedConfigFile, $config, ...etc), which remains accessible within the app, thought the `global` keyword.
This PR close the access of those global variables in expressive by running inclusions within an anonymous scope in the `public/index.php`, and discourage forever usage of the `global` keyword.
=> Prevent global variables references

composer.json, src/ExpressiveInstaller/OptionalPackages.php, src/ExpressiveInstaller/config.php, test/ExpressiveInstallerTest/SetupDefaultAppTest.php
This patch updates the installer to also add the zend-expressive-tooling package *if* a modular application layout is selected initially.
Required upping the minimum requirement for zend-component-installer to `^0.7`, as the latest version of zend-expressive-tooling depends on that version or higher..
Fixes #134
=> Added zend-expressive-tooling to dev requirements

README.md
`composer run serve --timeout 0` will disable default 5 minutes timeout without resorting to env variables
=> Update composer serve instruction in README

.travis.yml, CHANGELOG.md, composer.json, src/ExpressiveInstaller/config.php
zend-expressive-helpers 4.0 updates to PSR-11 and PSR-15 interfaces, and, as such, is backwards incompatible with previous releases for purposes of extension. For purposes of consumption, which is what the skeleton does, it is fully backwards compatible.
Due to the BC breaks, new minor releases of each renderer were made that add support for the helpers 4.0 series.
As such, this patch updates to use zend-expressive-helpers 4.0, and to install the renderer versions compatible with that release.
Additionally
- it updates the zend-expressive-tooling minimum supported version to pick up the latest bugfixes.
- it updates the zend-expressive minimum supported version to pick up the latest bugfixes.
=> Update to zend-expressive-helpers 4.0

composer.json
The following now have stable 1.0 versions:
- zend-config-aggregator
- zend-component-installer
Further, the APIs of each are exactly the same as the last stable 0.X releases, meaning they are 100% compatible.
=> Updated to stable dependencies

composer.json
This should prevent issues with installation due to the webimpress/http-middleware-compatibility plugin.
Prior to this change, after the plugin triggered, an exception would occur in the installer.
=> Explicitly require http-middleware

composer.json
Using `composer serve` on WSL adds an extra `public` path so it can't find the `index.php` file. As the root path is already set, it's not needed in front of the index file.
=> Fix composer serve command on WSL

CHANGELOG.md, composer.json, src/ExpressiveInstaller/OptionalPackages.php, src/ExpressiveInstaller/Resources/config/container-auryn.php, src/ExpressiveInstaller/config.php, test/ExpressiveInstallerTest/ContainersTest.php
Auryn provides a powerful reflection-based injector. Although Auryn
itself does not implement PSR-11 a wrapper does exist for it.
Depends on changes from #160.
=> Add option to use Auryn as a container

composer.json
For some reason, the script was "updated" for the release-3.0.0 branch to `php -S 0.0.0.0:8080 -t public index.php`, which will not work (`index.php` is in the `public/` subdirectory, not the root directory).
Updates to make it work properly.
=> Fixes syntax of `composer serve` script

composer.json, src/ExpressiveInstaller/config.php, test/ExpressiveInstallerTest/SetupDefaultAppTest.php
This adds zend-expressive-tooling as a development requirement, and adds the composer script "expressive", resolving to `vendor/bin/expressive --ansi`.
Considering that the tooling provides support for creating middleware and modules, and will add more features in the future, this is a reasonably expected package to have available in the skeleton.
=> Adds zend-expressive-tooling as a development requirement

config/pipeline.php, public/index.php, src/ExpressiveInstaller/Resources/config/routes-full.php, src/ExpressiveInstaller/Resources/config/routes-minimal.php
This patch implements an idea [proposed by @Xerkus](https://github.com/zendframework/zend-expressive/pull/543#issuecomment-361419425): having the `pipeline.php` and `routes.php` files return _closures_, and updating `public/index.php` to capitalize on that in order to pass in arguments.
In this particular case, we pass the application, middleware factory, and PSR-11 container instances as arguments. This provides developers with all the tools they should need in order to create the pipeline and/or routes.
In essence, each file has the following statement:
```php
return function (Application $app, MiddlewareFactory $factory, ContainerInterface $container) : void {
};
```
This allows such things as:
- Using the `Zend\Stratigility\host()` utility:
```php
$app->pipe(host('api.example.com', …
```
=> Have pipeline and route files return closures

src/App/src/Handler/HomePageFactory.php, src/App/src/Handler/HomePageHandler.php, src/App/src/Handler/PingHandler.php, src/ExpressiveInstaller/OptionalPackages.php, src/ExpressiveInstaller/Resources/config/routes-full.php, src/ExpressiveInstaller/Resources/config/routes-minimal.php, src/ExpressiveInstaller/Resources/src/ConfigProvider.flat.php, src/ExpressiveInstaller/Resources/src/ConfigProvider.modular.php, test/AppTest/Handler/HomePageFactoryTest.php, test/AppTest/Handler/HomePageHandlerTest.php, test/AppTest/Handler/PingHandlerTest.php, test/ExpressiveInstallerTest/ProjectSandboxTrait.php, test/ExpressiveInstallerTest/RoutersTest.php
Since zend-expressive 3.0.0alpha2 and up support routing and piping to request handlers, we can adopt that practice and terminology for the shipped "middleware", which are actually handlers.
=> Refactor "Actions" to request handlers

CHANGELOG.md, composer.json, src/ExpressiveInstaller/OptionalPackages.php, src/ExpressiveInstaller/config.php, test/ExpressiveInstallerTest/OptionalPackagesTestCase.php, test/ExpressiveInstallerTest/ProcessAnswersTest.php, test/ExpressiveInstallerTest/UpdateRootPackageTest.php
Add packages to the zend-component-installer whitelist to allow silent installation without the inject package prompt. It pre-whitelists packages in composer.json which are installed by default and also whitelists selected packages and possible dependencies.
Depends on zendframework/zend-component-installer#48
Related zendframework/zend-component-installer#48
Closes #207
Closes #204
=> Whitelist all possible components installed by the installer

README.md, composer.json
This PR fixes the `composer serve` command as discussed in #196.
Closes #196
=> Fix the composer serve command for PHP 7.1.14+ and PHP 7.2.2+

config/pipeline.php, test/ExpressiveInstallerTest/ProjectSandboxTrait.php
This patch follows on zendframework/zend-expressive#559, and modifies the pipeline to directly refer to the `PathBasedRoutingMiddleware` instead of using the `ROUTE_MIDDLEWARE` constant. It's better and faster to use the canonical name, and the old name (to which the constant resolves) is an alias for purposes of aiding those upgrading from v2; since aliases resolve to the same instance as the canonical service, this remains backwards compatible.
=> Reverts usage of ROUTE_MIDDLEWARE constant

CHANGELOG.md, src/App/src/Handler/HomePageHandlerFactory.php, src/ExpressiveInstaller/Resources/src/ConfigProvider.flat.php, src/ExpressiveInstaller/Resources/src/ConfigProvider.modular.php, test/AppTest/Handler/HomePageFactoryTest.php
As the factory is used to create the "HomePageHandler" with "Handler" suffix, I think it is better to have factory named "HomePageHandlerFactory" with "Handler" inside it.
=> rename HomePageFactory to HomePageHandlerFactory

.travis.yml, composer.json, phpstan.installer.neon, src/ExpressiveInstaller/OptionalPackages.php
After having issues with previous alpha's (now fixed, see #220), why not benefit from phpstan to ensure the skeleton passes static analysis ? 
I think the skeleton should not be opinionated. So the changes I've made are only tested with travis (no composer scripts) and deps are removed after install. The drawback is that it's not totally accurate (tests does run prior to an actual installation).
So for now it's open for ideas... (travis build stages with real installs... ?).
*BTW, travis will probably stop to complaining after #229 is merged*
=> Proposal: add phpstan for installer

data/.gitignore
Add data/cache to gitkeep to prevent checkout of project to different location from throwing non-existent directories warning.
=> Add data/cache to gitkeep

composer.json, src/ExpressiveInstaller/OptionalPackages.php, test/ExpressiveInstallerTest/PromptForOptionalPackagesTest.php, test/ExpressiveInstallerTest/RequestInstallTypeTest.php
Since symfony/console 4 questions only accept a question string. Looking at its history, this was always the case and is wrong in the composer docblock.
see: https://github.com/symfony/console/blob/4.0/Question/Question.php#L37
see: https://github.com/composer/composer/blob/1.6/src/Composer/IO/IOInterface.php#L106
=>  Convert questions to a string, fixes #243

.travis.yml
The Travis jobs have been reporting errors with the `DEPS=lowest` target. I've found locally that when I switch from `composer update` to `composer install` when installing dependencies, the conflict reported by `update` disappears.
=> Fix installation issue with --prefer-lowest

test/AppTest/Handler/HomePageHandlerFactoryTest.php, test/AppTest/Handler/HomePageHandlerTest.php
When creating a fresh project using `composer create-project zendframework/zend-expressive-skeleton` two namespace imports in the PHPUnit tests are missing.
This has no functional impact but PHPStorm and other static analysis tools will complain.
=> Add missing ObjectProphecy imports

config/config.php, phpstan.installer.neon
This PR adds the support of [Swoole](https://www.swoole.co.uk/) overwriting some service configurations of [zend-expressive](https://github.com/zendframework/zend-expressive).
The configuration is injected via `Zend\Expressive\Swoole\ConfigProvider` if [zend-expressive-swoole](https://github.com/zendframework/zend-expressive-swoole) is installed.
This PR allows to execute Swoole without any change on `public/index.php`. We can just run the follows:
```bash
php public/index.php
```
To execute an Expressive application with Swoole.
=> Added Swoole config, if installed

composer.json
This PR moves the security-advisories to composer's require-dev section.
=> Move security-advisories to require-dev

test/AppTest/Handler/HomePageHandlerFactoryTest.php
This PR removes the requested name being passed to the factory. The requested name is not used and it was wrong anyway. It should have been the FQN of the handler and not the container. Also it should be
passed as the second argument as the third one is for options.
=> Don't pass the requested name to the factory

CHANGELOG.md, src/ExpressiveInstaller/OptionalPackages.php, test/ExpressiveInstallerTest/RemoveInstallerTest.php
This PR removes the phpstan leftovers from composer.
Fixes #261 
Fixes #263
=> Remove phpstan leftovers

src/App/src/Handler/HomePageHandler.php
Provide a narrative description of what you are trying to accomplish:
Completeness of support for PHP-DI as DI Container
=> Properly detect PHP-DI container

composer.json, src/App/src/Handler/HomePageHandler.php, src/ExpressiveInstaller/Resources/config/container-php-di.php, src/ExpressiveInstaller/config.php
@xtreamwayz suggested a namespace change for [zend-di-config](https://github.com/elie29/zend-di-config) [#31](https://github.com/elie29/zend-di-config/issues/31). 
Starting from v4, the namespace will be Elie\PHPDI\Config instead of Zend\DI\Config.
A migration document from v3 to v4 has been created [here](https://github.com/elie29/zend-di-config/blob/master/docs/migration-4.0.md)
=> Updates zend phpdi to v4 [BC]
